### ISSUE TITLE
jekyll-watch not working

### ISSUE THREAD

**Issue by TimonVS** [VARIANTE/generator-vars-jekyll#4] opened 2015-11-09 21:26 UTC
I'm getting the following error: `Dependency Error: Yikes! It looks like you don't have jekyll-watch or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-watch' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!`.

I tried adding `jekyll-watch` to the Gemfile. And I also tried installing jekyll-watch globaly, but it doesn't seem to be working. Could this be a problem with Jekyll 3.0?

**Comment by andrewscwei** [comment] 2015-11-09 22:06
I am unable to reproduce the error you mentioned. This is the list of gems I have after running `bundle install`:

```
Gems included by the bundle:
  * bundler (1.10.6)
  * colorator (0.1)
  * ffi (1.9.10)
  * jekyll (3.0.0)
  * jekyll-sass-converter (1.3.0)
  * jekyll-watch (1.3.0)
  * kramdown (1.9.0)
  * liquid (3.0.6)
  * listen (3.0.4)
  * mercenary (0.3.5)
  * rb-fsevent (0.9.6)
  * rb-inotify (0.9.5)
  * rouge (1.10.1)
  * safe_yaml (1.0.4)
  * sass (3.4.19)
```

As you can see, `jekyll-watch` is one of `jekyll`'s dependencies (even for 3.0) so there shouldn't be a need to explicitly specify it in `Gemfile`. I'm not sure what's happening here. Are you able to verify the installed gems in `vendor/bundle/ruby/{version}/gems` of your generated project?

**Comment by andrewscwei** [comment] 2015-11-14 23:52
Closing this issue because it cannot be reproduced and there are no follow-up reports.

**Closed as completed by andrewscwei** 2015-11-14 23:52 UTC
